apiVersion: v1
kind: Pod
metadata:
  name: busybox
  namespace: busybox
spec:
  containers:
  - image: busybox
    command:
      - sleep
      - "300"
    imagePullPolicy: IfNotPresent
    name: busybox
  restartPolicy: Never